### ISSUE TITLE
Filter out commit notifications

### ISSUE THREAD

**Issue by msjtheriault** [gitify-app/gitify#2070]
### 📝 Provide a description of the new feature

Hi! I've been using gitify for a few months now, and it's really neat!

Is there a way to filter out notifications when someone pushes commits that updates a pull request?

Here's my use case. My team and I push code into branches of a repository, and then we ask other members for code review using pull requests. I do get a notification when I'm asked for a review, but then I also get one for every subsequent commit that's pushed onto that branch. I don't care about these commits, I only want to get notified when I'm asked for a review or when I'm tagged.

Thanks :)

**Comment by setchy** [comment]
Thanks for being a Gitify user @msjtheriault.

In the above scenario, what do these notifications look like within the GitHub Web UI - https://github.com/notifications

I was thinking that our `Reason` filters may suitable, but would need to confirm

**Comment by msjtheriault** [comment]
![Image](https://github.com/user-attachments/assets/760e5576-6d77-41ba-93ff-0253f0d980d3)

Notifications inside the red square were all obviously triggered by a commit that was pushed by a team mate.

I think the "reason" is the reason I'm subscribed to everything that happens. 

I found these options in Github, but they don't help:

![Image](https://github.com/user-attachments/assets/11bb8566-3e57-41e1-ae74-88761a9c7798)

**Comment by setchy** [comment]
I don't _think_ the GitHub API response contains attributes to help filter by these types of notifications.

But if you have time to have a closer look and can find something useful that would be great

**Comment by msjtheriault** [comment]
Hmm, you're right, there's notmuch to filter on that... There might be a way though by interpreting `notification.subject.latest_comment_url`. Here are some examples:

Triggered by a comment:

```json
    "subject": {
      "title": "Gnome 46 Support",
      "url": "https://api.github.com/repos/OttoAllmendinger/gnome-shell-screenshot/issues/206",
      "latest_comment_url": "https://api.github.com/repos/OttoAllmendinger/gnome-shell-screenshot/issues/comments/3039247256",
      "type": "Issue"
    },
```

Triggered by a branch delete in a pull request:

```json
    "subject": {
      "title": "17.0 activity viewer enhancement",
      "url": "https://api.github.com/repos/metalsartigan/odoo_addons/pulls/212",
      "latest_comment_url": null,
      "type": "PullRequest"
    },
```

Triggered by a some other event in a pull request, I lost the actual reason but I'm pretty sure it was a branch merge.

```json
    "subject": {
      "title": "#TP3601 Add new test for mail activity filter when we call copy method without extra_domain",
      "url": "https://api.github.com/repos/metalsartigan/odoo_addons/pulls/214",
      "latest_comment_url": "https://api.github.com/repos/metalsartigan/odoo_addons/pulls/214",
      "type": "PullRequest"
    },

```

There's one catch: if you go to github and mark a read notification as unread, then `latest_comment_url` gets set to null. 😓 

Well, one other way would be to fetch and parse `latest_comment_url` when it is present, and filter on that?

**Comment by setchy** [comment]
Thanks for taking a deeper look, @msjtheriault.

How about within the API response of https://api.github.com/repos/metalsartigan/odoo_addons/pulls/214, are there any attributes there that could be useful?

**Comment by msjtheriault** [comment]
It's all info about the PR it self: who created it, when, what's the PR message, the head commit, the branch, repository.

Although...

```json
    "_links": {
        "self": {
            "href": "https://api.github.com/repos/metalsartigan/odoo_addons/pulls/214"
        },
        "html": {
            "href": "https://github.com/metalsartigan/odoo_addons/pull/214"
        },
        "issue": {
            "href": "https://api.github.com/repos/metalsartigan/odoo_addons/issues/214"
        },
        "comments": {
            "href": "https://api.github.com/repos/metalsartigan/odoo_addons/issues/214/comments"
        },
        "review_comments": {
            "href": "https://api.github.com/repos/metalsartigan/odoo_addons/pulls/214/comments"
        },
        "review_comment": {
            "href": "https://api.github.com/repos/metalsartigan/odoo_addons/pulls/comments{/number}"
        },
        "commits": {
            "href": "https://api.github.com/repos/metalsartigan/odoo_addons/pulls/214/commits"
        },
        "statuses": {
            "href": "https://api.github.com/repos/metalsartigan/odoo_addons/statuses/ff4371475f6f3ce962c8990d4d84aaeae3ee847e"
        }
    },
```

There might be something that could be done with `prdata._links.comments`, `prdata._links.review_comments`. They return lists of comments.

Well that's starting to feel more like a PR thread parser than a notification filter ;)

**Comment by setchy** [comment]
Agree, it does seem a bit of a reach. 

Thinking out loud, what if notifications could be "grouped" - would that achieve something similar to what you were looking for?  

I implemented something like this recently for [atlassify](https://github.com/setchy/atlassify), but unlike GitHub, in Atlassian notifications its a first-class concept

**Comment by msjtheriault** [comment]
Nice! Although it wouldn't help much for my use case. I would still get notifications when someone pushes commits. Less, but still.

I think what I'm trying to achieve is at minimum to get notifications when someone actually wants to reach me specifically. I guess I could unsbscribe every time I get a notification. That could work, is only one click, and I'll get subscribed again when I'm tagged or assigned as reviewer.

Oh well!

That being said, a tool to follow comment threads would be nice though ;) It sounds so simple, yet is probably very complex to implement...
